### ISSUE TITLE
华为ICT创新赛

### ISSUE THREAD

**Issue by vesper1012** [Fangjin98/ICTdemo#1]
您好：
打扰了～
我是华为21年创新赛的选手，但是由于没有得到很好的指导，对我们的作品有些一筹莫展；
我们的算法是“行人重识别”，能够在图像模糊光照差别等情况下识别目标，适用于多摄像头的大型场景，但是我们一直觉得算法很难落地，一直不知道我们能用这个算法到底能解决什么问题；
可否请您做一下指点呢～

**Comment by Fangjin98** [comment]
你好，我现在的研究方向是网络方向，对你这个方向的问题和场景都没有什么了解，所以恐怕给不了什么建议，不好意思。

**Comment by vesper1012** [comment]
您好：
没关系的~ 感谢回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FangJin98/ICTdemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FangJin98/ICTdemo] 华为ICT创新赛 (Issue #1)





 
你好，我现在的研究方向是网络方向，对你这个方向的问题和场景都没有什么了解，所以恐怕给不了什么建议，不好意思。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
